site_name: CREOLE 0.1
repo_url: https://github.com/amaque/CREOLE
edit_uri: tree/master/docs

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  
markdown_extensions:
  - attr_list
  
extra_css:
  - stylesheets/extra.css
